# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: "none"

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  csv: ^5.0.2
  lottie: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/
    - assets/icons/
